[binaries] update (*) to `dmenu` vs `fzf/fzy`

diff --git a/binaries/.local/bin/dictionary b/binaries/.local/bin/dictionary
--- a/binaries/.local/bin/dictionary
+++ b/binaries/.local/bin/dictionary
@@ -1,80 +1,59 @@
 #!/usr/bin/env bash
 
-open_sdcv() {
-	sdcv
-}
+command -v dmenu >/dev/null 2>&1 || { echo "ERROR: dmenu bin is required." >&2 ; exit 1 ; }
+command -v term-window >/dev/null 2>&1 || { echo "ERROR: term-window bin is required." >&2 ; }
+
+open_sdcv() { sdcv ; }
 
 lookup_offline_def() {
 	word="$1"
 	if [ -z "$word" ]; then
-		printf "(sdcv) Definition for: "
-		read -r word
+		word=$(echo "" | dmenu -p "[sdcv] Definition for: ")
 	fi
-	sdcv -n "$word" | vim - -R
+	if [[ -n "$word" ]]; then
+	   	term-window exe "sdcv -n $word | vim - -R"
+	else
+		term-window exe "sdcv"
+	fi
 }
 
 lookup_online_def() {
 	word="$1"
 	if [ -z "$word" ]; then
-		printf "(ONLINE) Definition for: "
-		read -r word
+		word=$(echo "" | dmenu -p "[dict] Definition for: ")
 	fi
-	dict "$word" | vim - -R
+	[[ -n "$word" ]] && term-window exe "dict $word | vim - -R" || exit 1
 }
 
 lookup_synonym() {
 	word="$1"
 	if [ -z "$word" ]; then
-		printf "Synonyms for: "
-		read -r word
+		word=$(echo "" | dmenu -p "[synonyms] Synonyms for: ")
 	fi
 
 	command -v synonyms >/dev/null 2>&1 || {
-		echo "ERROR: synonyms is required, but is not in PATH. Make sure you have synonyms bin." >&2
+		echo "ERROR: synonyms bin is required." >&2
 		exit 1
 	}
-	synonyms $word ; read
+	[[ -n "$word" ]] && term-window exe "synonyms $word ; read" || exit 1
 
 	# WEB SEARCH ALTERNATIVE:
 	# www "$word !synonyms" &
 }
 
-prompt() {
-	opts=(
-		"definition :: Lookup Definition |OFFLINE :: sdcv|"
-		"synonym :: Lookup Synonym (Open in Browser)"
-		"sdcv :: Open SDCV APP (OFFLINE)"
-		"dict :: Lookup Definition |ONLINE: dict|"
-	)
-	selected=$(printf "%s\n" "${opts[@]}" | fzy)
-	action=${selected%% ::*}
-	case $action in
-		definition) lookup_offline_def ;;
-		sdcv) open_sdcv ;;
-		synonym) lookup_synonym ;;
-		dict) lookup_online_def ;;
-		*) exit 0
+opts() {
+	case "$1" in
+		def*|sdcv|offline) open_sdcv "$2" ;;
+		dict*|online) lookup_online_def "$2" ;;
+		syn*) lookup_synonym "$2" ;;
 	esac
 }
 
-dmenuopts() {
-	opts=( "definition" "synonyms" "sdcv" "dict")
-	selected=$(printf "%s\n" "${opts[@]}" | dmenu)
-	term-window dictionary "$selected"
-}
+if [[ -n "$1" ]]; then
+	opts "$@"
+else
+	opts=("definition" "synonyms" "sdcv" "dict")
+	sel=$(printf "%s\n" "${opts[@]}" | dmenu)
+	opts "$sel"
+fi
 
-case "$1" in
-	sdcv) open_sdcv ;;
-	offline) open_sdcv ;;
-
-	def*) lookup_offline_def "$2" ;;
-
-	syn*) lookup_synonym "$2" ;;
-
-	dict*) lookup_online_def "$2" ;;
-	online) lookup_online_def "$2" ;;
-
-	dmenu) dmenuopts "$@" ;;
-
-	*) prompt ;;
-esac
diff --git a/binaries/.local/bin/pass-copy b/binaries/.local/bin/pass-copy
--- a/binaries/.local/bin/pass-copy
+++ b/binaries/.local/bin/pass-copy
@@ -1,78 +1,59 @@
-#!/usr/bin/env bash 
+#!/usr/bin/env bash
 
-if ! command -v fzy >/dev/null 2>&1; then
-	echo "fzy required"
-	exit 1
-fi
-if ! command -v pass >/dev/null 2>&1; then
-	echo "pass required"
-	exit 1
-fi
+command -v dmenu >/dev/null 2>&1 || { echo "ERROR: dmenu bin is required." >&2 ; exit 1 ; }
+command -v pass >/dev/null 2>&1 || { echo "pass required" ; exit 1 ; }
+command -v term-window >/dev/null 2>&1 || { echo "ERROR: term-window bin is required." >&2 ; }
 
-select_pass_type() {
-	printf "pass\nusername\notp\nurl" | fzy
-}
-
-select_pass_file() {
-	find . -type f -name '*.gpg' | sed 's/\.gpg//' | sed 's/^\.\///' | sort | fzy
-}
-
-select_username_file() {
-	find . -type f -name '*username.gpg' | sed 's/\.gpg//' | sed 's/^\.\///' | sort | fzy 
-}
-
-select_otp_file() {
-	find . -type f -name '*otp.gpg' | sed 's/\.gpg//' | sed 's/^\.\///' | sort | fzy
-}
-
-select_url_file() {
-	find . -type f -name '*url.gpg' | sed 's/\.gpg//' | sed 's/^\.\///' | sort | fzy
-}
+passfiles() { find . -type f -name '*.gpg' | sed 's/\.gpg//' | sed 's/^\.\///' | sort ; }
+usernamefiles() { find . -type f -name '*username.gpg' | sed 's/\.gpg//' | sed 's/^\.\///' | sort ; }
+otpfiles() { find . -type f -name '*otp.gpg' | sed 's/\.gpg//' | sed 's/^\.\///' | sort ; }
+urlfiles() { find . -type f -name '*url.gpg' | sed 's/\.gpg//' | sed 's/^\.\///' | sort ; }
 
 # MAIN
-cd $HOME/.password-store || { echo "Failed to change directoy to ~/.password-store."; exit 1; }
+cd "$HOME/.password-store" || {
+	echo "Failed to change directoy to ~/.password-store." >&2 ; exit 1;
+}
 
-echo "[PASS] Select pass type:"
-PASS_TYPE=$(select_pass_type)
-echo $PASS_TYPE
-if [ -z "$PASS_TYPE" ]; then
-	echo "No pass type selected."
-	exit 0
+opts() {
+	case "$1" in
+		pass)
+			spass=$(passfiles | dmenu -p "PASS" -l 5)
+			[[ -z $spass ]] && { echo "No pass selected." ; exit 0 ; }
+			pass show -c "$spass"
+			;;
+		username)
+			susername=$(usernamefiles | dmenu -p "USERNAMES" -l 5)
+			[[ -z $susername ]] && { echo "No username selected." ; exit 0 ; }
+			pass show -c "$susername"
+			;;
+		otp)
+			sotp=$(otpfiles | dmenu -p "OTP" -l 5)
+			[[ -z $sotp ]] && { echo "No OTP selected." ; exit 0 ; }
+			pass otp show -c "$sotp"
+			;;
+		url)
+			surl=$(urlfiles | dmenu -l 5)
+			[[ -z $surl ]] && { echo "No URL selected." ; exit 0 ; }
+			pass show -c "$surl"
+			;;
+		insert)
+			name=$(passfiles | dmenu -p "insert new pass" -l 5)
+			term-window exe "pass-insert '$name'"
+ 			;;
+		generate)
+			newpass=$(passfiles | dmenu -p "GENERATE NEW PASS" -l 5)
+			[[ -n "$newpass" ]] && pass generate "$newpass"
+			;;
+		\|) exit 0 ;;
+		*) opts ;;
+	esac
+}
+
+if [[ -n "$1" ]]; then
+	opts "$@"
+else
+	prompt="[PASS]"
+	opts=("pass" "otp" "username" "url" "|" "insert" "generate" )
+	sel=$(printf "%s\n" "${opts[@]}" | dmenu -p "$prompt")
+	[[ -n $sel ]] && opts "$sel" || exit 0
 fi
-
-case "$PASS_TYPE" in
-	pass)
-		PASS_FILE=$(select_pass_file)
-		if [ -z "$PASS_FILE" ]; then
-			echo "No pass selected."
-			exit 0
-		fi
-		pass show -c "$PASS_FILE"
-		;;
-	username)
-		PASS_USERNAME_FILE=$(select_username_file)
-		if [ -z "$PASS_USERNAME_FILE" ]; then
-			echo "No username selected."
-			exit 0
-		fi
-		pass show -c "$PASS_USERNAME_FILE"
-		;;
-	otp)
-		PASS_OTP_FILE=$(select_otp_file)
-		if [ -z "$PASS_OTP_FILE" ]; then
-			echo "No OTP selected."
-			exit 0
-		fi
-		pass otp show -c "$PASS_OTP_FILE"
-		;;
-	url)
-		PASS_URL_FILE=$(select_url_file)
-		if [ -z "$PASS_URL_FILE" ]; then
-			echo "No URL selected."
-			exit 0
-		fi
-		pass show -c "$PASS_URL_FILE"
-		;;
-	*)
-		exit 1
-esac
